language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - phpunit

matrix:
  allow_failures:
    - php: hhvm

